version: '3.8'

services:
    kafka:
        platform: linux/amd64
        image: bitnami/kafka:3.7.0
        container_name: kafka
        networks:
          - kafka-net
        ports:
          - "9092:9092"
          - "9093:9093"
          - "9094:9094"
        volumes:
          - kafka-data:/bitnmai/kafka
        environment:
          - KAFKA_CFG_PROCESS_ROLES=broker,controller
          - KAFKA_CFG_NODE_ID=1
          - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
          - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
          - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  kafka-data:

networks:
  kafka-net: